# NEEDED INFORMATION:
# - domain
# - username
# - temporary password? (or a way to generate one and give it to the user)
# - bucket
# - region
# - key
# - secret
#
# snap install nextcloud && nextcloud.manual-install "$USERNAME" "$PASSWORD" && nextcloud.occ config:system:set trusted_domains 1 --value="$DOMAIN" && ufw allow 80,443/tcp && nextcloud.enable-https lets-encrypt || exit 1

# nextcloud.occ maintenance:mode --on || exit 1

# sed -i 's/^);$//' $CONFIG_FILE || exit 1
# printf "'objectstore' => array(\n        'class' => '\\\\OC\\\\Files\\\\ObjectStore\\\\S3',\n        'arguments' => array(\n                'bucket' => '$BUCKET',\n                'key'    => '$KEY',\n                'secret' => '$SECRET',\n                'hostname' => '$REGION.digitaloceanspaces.com',\n                'region' => '$REGION',\n                'port' => 443,\n                'use_ssl' => true,\n),\n),\n);" >> $CONFIG_FILE || exit 1

# nextcloud.occ maintenance:mode --off || exit 1
